//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebgridPagingSortingFiltering.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kisiler
    {
        public int Id { get; set; }
        public int GrupId { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Unvani { get; set; }
        public string FirmaUnvani { get; set; }
        public Nullable<decimal> IsTel { get; set; }
        public Nullable<decimal> Cep { get; set; }
        public Nullable<decimal> Fax { get; set; }
        public string Adres { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
    
        public virtual Gruplar Gruplar { get; set; }
    }
}
